
server.port: 8083

spring.datasource.url: jdbc:mysql://localhost:3306/rating_microservice
spring.datasource.username: root
spring.datasource.password: root@123

spring.jpa.database = MYSQL
spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto=update

jpa.hibernate.show-sql :true

eureka.instance.prefer-ip-address: true
eureka.client.register-with-client: true
eureka.client.feth-registry: true

spring.application.name: RATING-SERVICE